apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-frontend
  namespace: fullstack-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-frontend
  template:
    metadata:
      labels:
        app: nginx-frontend
    spec:
      containers:
      - name: nginx-frontend
        image: boluadesina/nginx-frontend:latest
        ports:
        - containerPort: 80
