apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: fullstack-app
spec:
  selector:
    app: nginx-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
  # nodePort: 30080
